# 04_normalisation

In [2]:
import json
import pandas as pd

# Afficher toutes les colonnes (sans limite)
pd.set_option("display.max_columns", None)

## Chargement des données

In [3]:
def charger_offres(path):
    '''
    Charge un fichier de données en format json à partir de sa localisation (chemin).
    Renvoie une liste.
    '''
    with open(path, "r", encoding="utf-8") as f:
        offres = json.load(f)
        return offres

# fichiers de données 
path_ft = "../data/processed/francetravail/offres_20260401_092159.json"
path_wttj = "../data/processed/welcometothejungle/offres_20260401_092124.json"

# charger offres France travail et Welcome to the jungle
offres_ft = charger_offres(path_ft)
offres_wttj = charger_offres(path_wttj)

print(f"{len(offres_ft)} offres FT chargées")
print(f"{len(offres_wttj)} offres WTTJ chargées")

# Chargement des données dans une dataframe
offres_ft_df = pd.DataFrame(offres_ft)
offres_wttj_df = pd.DataFrame(offres_wttj)

500 offres FT chargées
60 offres WTTJ chargées

## Exploration des données

In [4]:
def rechercher_duplicates(df):
    # Check number of rows before removing duplicates
    print(f"Number of rows : {len(df)}\n")

    # # Compute the number of duplicated rows
    # print(f"Number of duplicated rows : {df.duplicated().sum()}\n")

def get_missing_data(data):       
    # Counting the percentage of NaN for each column
    missing_data = data.isnull().sum().sort_values(ascending=False)/len(data)*100 #NaN percentage for each column

    # missing_data
    missing_data = missing_data[missing_data > 0]

    #Missing data column names
    missing_cols = missing_data.index.values.tolist()

    #Show missing data in percent
    if len(missing_data)>0:
        print("missing data (isnull) detected are as follows:")
        display(missing_data)
    else:
        display("no missing data detected\n")

def explore(df):
    #Numerical Features
    numerical_features = df.select_dtypes(include = 'number').columns.values.tolist()
    
    print(f"Shape is : {df.shape}\n")

    display(df.sample(5))

    display(df.info())
    print("\n")
    
    if numerical_features:
        print("Description is : \n")
        display(df.describe())
    else : 
        print("No numerical features to describe.\n")

    get_missing_data(df)

### France Travail

In [5]:
# Champs obligatoires
champs_obligatoires_ft = ["id", "source","titre", "entreprise","description",
                       "competences","localisation_ville","type_contrat",
                       "type_contrat_libelle","date_publication","url"]

# Champs recommandés (il manque missions et télétravail chea france travail)
champs_recommandes_ft = ["salaire_min", "salaire_max","experience_min",
                      "experience_exige","teletravail","secteur",
                      "localisation_dept","latitude","longitude","nb_employes"]


print("\n*********************** CHAMPS OBLIGATOIRES FT  *************************")
df_obligatoire_ft = offres_ft_df[champs_obligatoires_ft]
explore(df_obligatoire_ft)
print("\n***********************************************************************\n")

print(" \n*********************** CHAMPS RECOMMANDES FT *************************")
df_reco_ft = offres_ft_df[champs_recommandes_ft]
explore(df_reco_ft)
print("\n***********************************************************************\n")

# df_reco_ft.duplicated()
# df_obligatoire_ft.duplicated()

*********************** CHAMPS OBLIGATOIRES FT  *************************
Shape is : (500, 11)

,id,source,titre,entreprise,description,competences,localisation_ville,type_contrat,type_contrat_libelle,date_publication,url
162,0652209,francetravail,Data manager,Biocodex - CB,Au sein de l'équipe Global Regulatory Affairs ...,[],Gentilly,CDD,CDD - 6 Mois,2026-03-24,https://candidat.francetravail.fr/offres/reche...
499,7199274,francetravail,Responsable big data,NaN,descriptif du posteDans le cadre du déploiemen...,[],Clichy,MIS,Intérim - 3 Mois,2025-12-29,https://candidat.francetravail.fr/offres/reche...
28,0972862,francetravail,Data engineer,NaN,"Le Groupement Les Mousquetaires, ce sont 7 ens...",[],Châtillon,CDI,CDI,2026-03-31,https://candidat.francetravail.fr/offres/reche...
356,0082846,francetravail,Data manager,NaN,Description du poste :\nEn tant qu'organisateu...,[],Hauts-De-Seine,CDI,CDI,2026-03-10,https://candidat.francetravail.fr/offres/reche...
98,0723352,francetravail,Data engineer,NaN,RejoignezVISEOet explorez un univers de possib...,[],Toulouse,CDI,CDI,2026-03-25,https://candidat.francetravail.fr/offres/reche...

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    500 non-null    str
 1   source                500 non-null    str
 2   titre                 500 non-null    str
 3   entreprise            118 non-null    str
 4   description           500 non-null    str
 5   competences           500 non-null    object
 6   localisation_ville    500 non-null    str
 7   type_contrat          500 non-null    str
 8   type_contrat_libelle  500 non-null    str
 9   date_publication      500 non-null    str
 10  url                   500 non-null    str
dtypes: object(1), str(10)
memory usage: 43.1+ KB

None

No numerical features to describe.

missing data (isnull) detected are as follows:

entreprise    76.4
dtype: float64

***********************************************************************


*********************** CHAMPS RECOMMANDES FT *************************
Shape is : (500, 10)

,salaire_min,salaire_max,experience_min,experience_exige,teletravail,secteur,localisation_dept,latitude,longitude,nb_employes
337,NaN,NaN,NaN,D,None,,NaN,NaN,NaN,NaN
207,NaN,NaN,2.0,E,None,,14000,49.197885,-0.346875,NaN
54,NaN,NaN,NaN,E,None,,NaN,NaN,NaN,NaN
163,NaN,NaN,2.0,E,None,,14000,49.197885,-0.346875,NaN
23,NaN,NaN,NaN,D,None,,31000,43.572331,1.403040,NaN

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   salaire_min        110 non-null    float64
 1   salaire_max        110 non-null    float64
 2   experience_min     248 non-null    float64
 3   experience_exige   500 non-null    str
 4   teletravail        0 non-null      object
 5   secteur            500 non-null    str
 6   localisation_dept  412 non-null    str
 7   latitude           403 non-null    float64
 8   longitude          403 non-null    float64
 9   nb_employes        62 non-null     str
dtypes: float64(5), object(1), str(4)
memory usage: 39.2+ KB

None

Description is :

        salaire_min    salaire_max  experience_min    latitude   longitude
count    110.000000     110.000000      248.000000  403.000000  403.000000
mean   42284.381818   51045.109091        2.774194   47.081612    1.636498
std    18635.934285   23089.405423        2.017489    4.650928    7.328400
min      795.000000    1400.000000        0.000000  -21.035946  -90.224968
25%    36250.000000   45000.000000        2.000000   45.766184   -0.029099
50%    45000.000000   55000.000000        2.000000   48.409920    2.275131
75%    50000.000000   65000.000000        4.000000   48.887956    3.101533
max    80000.000000  100000.000000       10.000000   51.041327   55.298272

missing data (isnull) detected are as follows:

teletravail          100.0
nb_employes           87.6
salaire_max           78.0
salaire_min           78.0
experience_min        50.4
latitude              19.4
longitude             19.4
localisation_dept     17.6
dtype: float64

***********************************************************************

### Welcome to the jungle

In [6]:
# Champs obligatoires (il manque le champ compétences à WTTJ)
champs_obligatoires_wttj = ["id","source","titre","entreprise","description",
                            "localisation_ville","type_contrat",
                            "date_publication","url"]

# Champs recommandés (il manque missions et télétravail chea france travail)
champs_recommandes_wttj = ["salaire_min", "salaire_max","experience_min",
                           "teletravail","secteur","localisation_region",
                           "latitude","longitude","nb_employes","missions"]



print(" *********************** CHAMPS OBLIGATOIRES WTTJ  *************************")
df_obligatoire_wttj = offres_wttj_df[champs_obligatoires_wttj]
explore(df_obligatoire_wttj)
print("\n***********************************************************************\n")

print(" *********************** CHAMPS RECOMMANDES WTTJ *************************")
df_reco_wttj = offres_wttj_df[champs_recommandes_wttj]
explore(df_reco_wttj)
print("\n***********************************************************************\n")

 *********************** CHAMPS OBLIGATOIRES WTTJ  *************************
Shape is : (60, 9)

,id,source,titre,entreprise,description,localisation_ville,type_contrat,date_publication,url
24,7c24ca37-36d5-49f0-a5f2-4e45d279861d,welcometothejungle,Data Engineer (H/F),Witco,"Rejoins Witco, une entreprise dynamique en ple...",Paris,CDI,2026-03-30,https://www.welcometothejungle.com/fr/companie...
29,0c75268e-e78c-4c92-bc5e-896d2c0ebf10,welcometothejungle,Stage - Consultant Data / IAG Ingénieur - Paris,Cartelis Conseil,Rejoins notre équipe en tant que stagiaire con...,Paris,Stage,2026-03-31,https://www.welcometothejungle.com/fr/companie...
33,e4cfab23-8d0a-4ae1-8bcf-f39258680f4f,welcometothejungle,Data Engineer,ADVANCED SCHEMA,Rejoignez notre équipe en tant que Data Engine...,Paris,CDI,2026-03-30,https://www.welcometothejungle.com/fr/companie...
37,cdd263e0-1605-4802-bcbc-a7134d679d28,welcometothejungle,Data visualization engineer,Société Générale,"Rejoignez la Société Générale, un leader mondi...",La Défense,Alternance,2026-03-27,https://www.welcometothejungle.com/fr/companie...
34,a9b9d867-9928-423d-89c9-110574651a4d,welcometothejungle,Senior Software Engineer – Data & Integration,Supervizor,"Join Supervizor, a fast-growing B2B SaaS compa...",Paris,CDI,2026-03-30,https://www.welcometothejungle.com/fr/companie...

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  60 non-null     str
 1   source              60 non-null     str
 2   titre               60 non-null     str
 3   entreprise          60 non-null     str
 4   description         60 non-null     str
 5   localisation_ville  60 non-null     str
 6   type_contrat        60 non-null     str
 7   date_publication    60 non-null     str
 8   url                 60 non-null     str
dtypes: str(9)
memory usage: 4.3 KB

None

No numerical features to describe.

'no missing data detected\n'

***********************************************************************

 *********************** CHAMPS RECOMMANDES WTTJ *************************
Shape is : (60, 10)

,salaire_min,salaire_max,experience_min,teletravail,secteur,localisation_region,latitude,longitude,nb_employes,missions
30,NaN,NaN,NaN,hybrid,Tech,Île-de-France,48.89918,2.28320,200.0,[Intervenir sur des problématiques métiers aut...
35,35000.0,45000.0,3.0,hybrid,Tech,NaN,48.00832,0.19745,16000.0,[Analyser des spécifications fonctionnelles et...
25,NaN,NaN,NaN,no,Tech,Île-de-France,48.70999,2.14990,80.0,[Concevoir et développer un Model Context Prot...
36,50000.0,NaN,5.0,hybrid,Tech,Île-de-France,48.88995,2.24718,70.0,"[Concevoir des architectures data robustes, sc..."
19,NaN,NaN,5.0,hybrid,Conseil / Audit,NaN,48.84069,2.34656,110.0,[Accompagner et conseiller les clients dans la...

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   salaire_min          10 non-null     float64
 1   salaire_max          9 non-null      float64
 2   experience_min       25 non-null     float64
 3   teletravail          60 non-null     str
 4   secteur              60 non-null     str
 5   localisation_region  50 non-null     str
 6   latitude             60 non-null     float64
 7   longitude            60 non-null     float64
 8   nb_employes          59 non-null     float64
 9   missions             60 non-null     object
dtypes: float64(6), object(1), str(3)
memory usage: 4.8+ KB

None

Description is :

,salaire_min,salaire_max,experience_min,latitude,longitude,nb_employes
count,10.000000,9.000000,25.000000,60.000000,60.000000,59.000000
mean,45420.000000,59022.222222,2.940000,46.682471,1.033061,20020.847458
std,19637.481169,27269.111545,1.838931,9.442790,6.432435,40146.174479
min,1200.000000,1200.000000,0.000000,-23.606300,-46.572120,12.000000
25%,40750.000000,50000.000000,1.000000,47.553803,2.182470,130.000000
50%,45000.000000,60000.000000,3.000000,48.850975,2.289035,750.000000
75%,53750.000000,85000.000000,4.000000,48.873658,2.346153,7550.000000
max,75000.000000,90000.000000,5.000000,49.184330,5.872380,190000.000000

missing data (isnull) detected are as follows:

salaire_max            85.000000
salaire_min            83.333333
experience_min         58.333333
localisation_region    16.666667
nb_employes             1.666667
dtype: float64

***********************************************************************